<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="ILRepack" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <PropertyGroup>
      <WorkingDirectory>$(MSBuildThisFileDirectory)</WorkingDirectory>
      <ILRepack>$(WorkingDirectory)..\ILRepack.exe</ILRepack>
      <InputAssemblies>$(OutputPath)$(TargetFileName)</InputAssemblies>
      <OutputAssembly>$(OutputPath)$(TargetFileName)</OutputAssembly>
    </PropertyGroup>
    <ItemGroup>
      <InputAssemblies Include="$(OutputPath)YamlDotNet.dll" />
      <InputAssemblies Include="$(OutputPath)Newtonsoft.Json.dll" />
    </ItemGroup>
    <Message Text="Merging assemblies with ILRepack..." Importance="High" />
    <Exec Command="$(ILRepack) /internalize /out:$(OutputAssembly) $(InputAssemblies) @(InputAssemblies, ' ')" WorkingDirectory="$(WorkingDirectory)" />
    <Message Text="ILRepack completed." Importance="High" />
  </Target>
</Project>
