<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="ILRepack" AfterTargets="Build">
    <PropertyGroup>
      <ILRepackExe>$(MSBuildThisFileDirectory)..\ILRepack.exe</ILRepackExe>
      <LibDir>$(MSBuildThisFileDirectory)..\0libDep</LibDir>
      <MergedOutput>$(MSBuildThisFileDirectory)bin\$(Configuration)\$(AssemblyName).merged.dll</MergedOutput>
      <MainDll>$(MSBuildThisFileDirectory)bin\$(Configuration)\$(AssemblyName).dll</MainDll>
      <YamlDll>$(MSBuildThisFileDirectory)bin\$(Configuration)\YamlDotNet.dll</YamlDll>
      <ConfigSyncDll>$(MSBuildThisFileDirectory)bin\$(Configuration)\ConfigSyncAPI.dll</ConfigSyncDll>
      <JewelcraftingDll>$(MSBuildThisFileDirectory)bin\$(Configuration)\JewelcraftingAPI.dll</JewelcraftingDll>
      <DeployTarget>C:\Program Files (x86)\Steam\steamapps\common\Valheim\BepInEx\plugins\OdinPlus.dll</DeployTarget>
    </PropertyGroup>
    <Message Text="ILRepack: merging YamlDotNet + ConfigSyncAPI + JewelcraftingAPI into $(AssemblyName).merged.dll ..." Importance="High" />
    <Exec Command="&quot;$(ILRepackExe)&quot; --internalize --lib:&quot;$(LibDir)&quot; --out:&quot;$(MergedOutput)&quot; &quot;$(MainDll)&quot; &quot;$(YamlDll)&quot; &quot;$(ConfigSyncDll)&quot; &quot;$(JewelcraftingDll)&quot;" />
    <Message Text="ILRepack: done. Deploying to BepInEx plugins..." Importance="High" />
    <Copy SourceFiles="$(MergedOutput)" DestinationFiles="$(DeployTarget)" ContinueOnError="true" />
  </Target>
</Project>
